### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by MarcusWolschon** [crystalpal/cropper#1]
What license have you chosen for this project?
There is none visible in README.md nor in the source code itself.

**Comment by jorenverspeelt** [comment]
GNU general public license. 
Have fun with it :)

**Comment by MarcusWolschon** [comment]
I don't see any change to the README.md or the code and this issue disapears from view the moment it's closed.
So the issue is not fixed until the license is documented anywhere a user may find it.

(Sorry, I can't have fun with it because for non-GPL projects I can't integrate GPL code.)
